In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [20]:
import torch

# 形状が(3, 1, 2)のテンソルを作成
x = torch.randn(3, 1, 2)
x_squeezed = x.squeeze()
x_unsqueezed = x.unsqueeze(0)

print(x)
print(x_squeezed)
print(x_unsqueezed)

RuntimeError: a Tensor with 6 elements cannot be converted to Scalar

In [21]:
# テンソルに対してindexの配列渡して、そのindexの要素を取得
idx = [0, 2]
print(x[idx])

tensor([[[ 0.9920,  1.6408]],

        [[-1.5058,  0.2638]]])


In [24]:
# argmaxの使い方
# 下記の3次元配列を使う
array = torch.tensor(
    [
        [
            [10, 20, 5, 3], 
            [4, 30, 6, 9], 
            [3, 80, 1, 2]
        ],
        [
            [5, 10, 20, 8],
            [3, 80, 1, 2],
            [30, 20, 10, 9],
        ]
    ]
)
print(f"array.shape={array.shape}") # (2, 3, 4)の3次元配列

# 3次元配列に対してaxisを指定する場合、
# axis=0のとき、1次元目の要素内の同じ行の要素の中で最大値のインデックスを返す
print(f"array.argmax(axis=0)=\n{array.argmax(axis=0)}")
# axis=1のとき、2次元目の行の要素の中で最大値のインデックスを返す
print(f"array.argmax(axis=1)=\n{array.argmax(axis=1)}")
# axis=2のとき、3次元目の配列の要素の中で最大値のインデックスを返す
print(f"array.argmax(axis=2)=\n{array.argmax(axis=2)}")

# axis=Noneの場合、1次元に変換して最大値のインデックスを返す
print(array.argmax())
# -1の場合、最後の次元(3次元ならaxis=2）に対して最大値のインデックスを返す
print(array.argmax(-1))

array.shape=torch.Size([2, 3, 4])
array.argmax(axis=0)=
tensor([[0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 0, 1, 1]])
array.argmax(axis=1)=
tensor([[0, 2, 1, 1],
        [2, 1, 0, 2]])
array.argmax(axis=2)=
tensor([[1, 1, 1],
        [2, 1, 0]])
tensor(9)
tensor([[1, 1, 1],
        [2, 1, 0]])


In [32]:
# topkの使い方
# 下記の1次元配列を使う
array = torch.tensor([10, 20, 5, 3, 4, 30, 6, 9, 3, 80, 1, 2])

# valuesとindicesを並び替えたうえで取得できる
topk = array.topk(5)
print(f"topk.values=\n{topk.values}")
print(f"topk.indices=\n{topk.indices}")

topk.values=
tensor([80, 30, 20, 10,  9])
topk.indices=
tensor([9, 5, 1, 0, 7])
