In [5]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [5]:
import torch

# 形状が(3, 1, 1, 2)のテンソルを作成
x = torch.randn(3, 1, 1, 2)

print('x', x.shape)
print(x)

# squeeze: 要素数が1の次元を削除
x_squeezed = x.squeeze()
print('x_squeezed', x_squeezed.shape)
print(x_squeezed)

# unsqueeze: 指定した次元に要素数1の次元を追加
x_unsqueezed = x.unsqueeze(0)
print('x_unsqueezed', x_unsqueezed.shape)
print(x_unsqueezed)

# テンソルに対してindexの配列渡して、そのindexの要素を取得
idx = [0, 2]
print(x[idx])

x torch.Size([3, 1, 1, 2])
tensor([[[[-0.9105,  1.5759]]],


        [[[ 1.9233, -0.9312]]],


        [[[ 0.1988,  0.2080]]]])
x_squeezed torch.Size([3, 2])
tensor([[-0.9105,  1.5759],
        [ 1.9233, -0.9312],
        [ 0.1988,  0.2080]])
x_unsqueezed torch.Size([1, 3, 1, 1, 2])
tensor([[[[[-0.9105,  1.5759]]],


         [[[ 1.9233, -0.9312]]],


         [[[ 0.1988,  0.2080]]]]])
tensor([[[[-0.9105,  1.5759]]],


        [[[ 0.1988,  0.2080]]]])


In [40]:
a = torch.tensor([
    [1, 2], 
    [3, 4]])
b = torch.tensor([
    [5, 6], 
    [7, 8]])

# テンソルの和
print('a + b', a + b)
# テンソルの差
print('a - b', a - b)

# テンソル要素感の積
print('a * b', a * b)

# テンソル同士の積
print('a @ b', a @ b)

# テンソルの要素の最大値
# 列方向の最大値
print('torch.max(a) dim=0', torch.max(a, dim=0))
# 行方向の最大値
print('torch.max(a) dim=1', torch.max(a, dim=1))

# 3次元テンソルのmax
c = torch.tensor([
    [
        [0, 0, 0.6, 0.9, 0.8], 
        [0.8, 0, 0, 0.7, 0]
    ]])
# 1次元目（バッチ数）の最大値. ただし、要素数が1つなのでそのまま値が返るかんじ
print('torch.max(c) dim=0', torch.max(c, dim=0))
# 2次元目（列方向）の最大値
col_max = torch.max(c, dim=1).values.squeeze()
print('col_max', col_max.shape, col_max)

# nonzero: 非ゼロ要素のインデックスを取得
nonzero_cols = col_max.nonzero().squeeze()
print('torch.max(c, dim=1).values.nonzero()', nonzero_cols.shape, nonzero_cols)

# 非ゼロ要素のインデックスで値を取り直す
print('col_max[nonzero_cols]', col_max[nonzero_cols])


a + b tensor([[ 6,  8],
        [10, 12]])
a - b tensor([[-4, -4],
        [-4, -4]])
a * b tensor([[ 5, 12],
        [21, 32]])
a @ b tensor([[19, 22],
        [43, 50]])
torch.max(a) dim=0 torch.return_types.max(
values=tensor([3, 4]),
indices=tensor([1, 1]))
torch.max(a) dim=1 torch.return_types.max(
values=tensor([2, 4]),
indices=tensor([1, 1]))
torch.max(c) dim=0 torch.return_types.max(
values=tensor([[0.0000, 0.0000, 0.6000, 0.9000, 0.8000],
        [0.8000, 0.0000, 0.0000, 0.7000, 0.0000]]),
indices=tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]))
col_max torch.Size([5]) tensor([0.8000, 0.0000, 0.6000, 0.9000, 0.8000])
torch.max(c, dim=1).values.nonzero() torch.Size([4]) tensor([0, 2, 3, 4])
col_max[nonzero_cols] tensor([0.8000, 0.6000, 0.9000, 0.8000])


In [7]:
# argmaxの使い方
# 下記の3次元配列を使う
array = torch.tensor(
    [
        [
            [10, 20, 5, 3], 
            [4, 30, 6, 9], 
            [3, 80, 1, 2]
        ],
        [
            [5, 10, 20, 8],
            [3, 80, 1, 2],
            [30, 20, 10, 9],
        ]
    ]
)
print(f"array.shape={array.shape}") # (2, 3, 4)の3次元配列

# 3次元配列に対してaxisを指定する場合、
# axis=0のとき、1次元目の要素内の同じ行の要素の中で最大値のインデックスを返す
print(f"array.argmax(axis=0)=\n{array.argmax(axis=0)}")
# axis=1のとき、2次元目の行の要素の中で最大値のインデックスを返す
print(f"array.argmax(axis=1)=\n{array.argmax(axis=1)}")
# axis=2のとき、3次元目の配列の要素の中で最大値のインデックスを返す
print(f"array.argmax(axis=2)=\n{array.argmax(axis=2)}")

# axis=Noneの場合、1次元に変換して最大値のインデックスを返す
print(array.argmax())
# -1の場合、最後の次元(3次元ならaxis=2）に対して最大値のインデックスを返す
print(array.argmax(-1))

array.shape=torch.Size([2, 3, 4])
array.argmax(axis=0)=
tensor([[0, 0, 1, 1],
        [0, 1, 0, 0],
        [1, 0, 1, 1]])
array.argmax(axis=1)=
tensor([[0, 2, 1, 1],
        [2, 1, 0, 2]])
array.argmax(axis=2)=
tensor([[1, 1, 1],
        [2, 1, 0]])
tensor(9)
tensor([[1, 1, 1],
        [2, 1, 0]])


In [8]:
# topkの使い方
# 下記の1次元配列を使う
array = torch.tensor([10, 20, 5, 3, 4, 30, 6, 9, 3, 80, 1, 2])

# valuesとindicesを並び替えたうえで取得できる
topk = array.topk(5)
print(f"topk.values=\n{topk.values}")
print(f"topk.indices=\n{topk.indices}")

topk.values=
tensor([80, 30, 20, 10,  9])
topk.indices=
tensor([9, 5, 1, 0, 7])


In [24]:
# 線形変換の例
# A = [[1, 2], [3, 4]], x = [1, 2]
A = torch.tensor([[1, 2], [3, 4]])
x = torch.tensor([1, 2])
Ax = torch.matmul(A, x)
print(f"Ax={Ax}")

Ax=tensor([ 5, 11])
eigenvalues, eigenvectors=((3.0, 2.0), [[1, -1.0], [1, -2.0]])
eigenvalue=(2.9999990463256836+0j), eigenvector=tensor([-0.7071-0.j,  0.7071+0.j])
eigenvalue=(2.000000476837158+0j), eigenvector=tensor([-0.4472+0.j,  0.8944+0.j])


In [25]:
# 固有ベクトル
# 行列 A = [[4, 1], [-2, 1]] の固有ベクトルを求める
# 固有値と固有ベクトルを求めるための手動計算
def find_eigenvalues(matrix):
    # 固有値は2次方程式 λ^2 - 5λ + 6 = 0 の解として計算される
    a = 1
    b = -5
    c = 6
    # 2次方程式の解
    discriminant = b**2 - 4*a*c
    lambda1 = (-b + discriminant**0.5) / (2*a)
    lambda2 = (-b - discriminant**0.5) / (2*a)
    return lambda1, lambda2

def find_eigenvector(matrix, eigenvalue):
    # 固有値を用いて固有ベクトルを求める
    # Ax = λx -> (A - λI)x = 0 となるxを見つける
    # 行列 (A - λI) を作成
    modified_matrix = [[matrix[0][0] - eigenvalue, matrix[0][1]], 
                       [matrix[1][0], matrix[1][1] - eigenvalue]]
    # この例では x = 1 を設定し y を解く
    x = 1
    y = -modified_matrix[0][0] * x / modified_matrix[0][1]
    return [x, y]

# 行列 A の定義
A = [[4, 1], [-2, 1]]
# 固有値を求める
eigenvalues = find_eigenvalues(A)
# 固有ベクトルを求める
eigenvectors = [find_eigenvector(A, ev) for ev in eigenvalues]

print(f"eigenvalues, eigenvectors={eigenvalues, eigenvectors}")


# 以下はpytorchを使った計算
# 計算式は、A * v = λ * v ここで、vは固有ベクトル、λは固有値
# 固有ベクトルは、A - λI の行列のnull spaceを求めることで求めることができる ここで、Iは単位行列
A = torch.tensor([[4, 1], [-2, 1]], dtype=torch.complex64)  # Convert A to complex data type
# 以下でpytorchを使わずに求めてみる
# 固有値を求める

# complex dataとは、実数部と虚数部を持つデータ型
# 固有ベクトルを求める
eigenvalues, eigenvectors = torch.linalg.eig(A)
# 固有値 eignevalues[i] に対して、固有ベクトル eigenvectors[:, i] が対応する
for i in range(len(eigenvalues)):
    print(f"eigenvalue={eigenvalues[i]}, eigenvector={eigenvectors[:, i]}")

eigenvalues, eigenvectors=((3.0, 2.0), [[1, -1.0], [1, -2.0]])
eigenvalue=(2.9999990463256836+0j), eigenvector=tensor([-0.7071-0.j,  0.7071+0.j])
eigenvalue=(2.000000476837158+0j), eigenvector=tensor([-0.4472+0.j,  0.8944+0.j])
