In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [18]:
import torch

# 形状が(3, 1, 2)のテンソルを作成
x = torch.randn(3, 1, 2)
x_squeezed = x.squeeze()
x_unsqueezed = x.unsqueeze(0)

print(x)
print(x_squeezed)
print(x_unsqueezed)

tensor([[[-0.6426, -0.4513]],

        [[ 0.1769, -0.0257]],

        [[-0.9018, -0.9362]]])
tensor([[-0.6426, -0.4513],
        [ 0.1769, -0.0257],
        [-0.9018, -0.9362]])
tensor([[[[-0.6426, -0.4513]],

         [[ 0.1769, -0.0257]],

         [[-0.9018, -0.9362]]]])
tensor([[[-0.6426, -0.4513]],

        [[-0.9018, -0.9362]]])


In [19]:
# テンソルに対してindexの配列渡して、そのindexの要素を取得
idx = [0, 2]
print(x[idx])

tensor([[[-0.6426, -0.4513]],

        [[-0.9018, -0.9362]]])
